import { TagType } from '../TagShape';

export const Example_TagList: TagType[] = [
  { name: 'Database' },
  { name: 'Inventory' },
  { name: 'Artificial Intelligence' },
  { name: 'Machine Learning' },
  { name: 'Deep Learning' },
  { name: 'SQL' },
  { name: 'NoSQL' },
  { name: 'Data Warehousing' },
  { name: 'Data Mining' },
  { name: 'Big Data' },
  { name: 'Cloud Storage' },
  { name: 'Data Modeling' },
  { name: 'ETL' },
  { name: 'Data Governance' },
  { name: 'Data Security' },
  { name: 'Inventory Management' },
  { name: 'Stock Control' },
  { name: 'Supply Chain' },
  { name: 'Warehouse Management' },
  { name: 'Order Fulfillment' },
  { name: 'Predictive Analytics' },
  { name: 'Natural Language Processing' },
  { name: 'Computer Vision' },
  { name: 'Reinforcement Learning' },
  { name: 'Neural Networks' },
  { name: 'AI Ethics' },
  { name: 'AI Applications' },
  { name: 'Data Science' },
  { name: 'Business Intelligence' },
  { name: 'Data Visualization' },
  { name: 'Data Integration' },
  { name: 'Data Quality' },
  { name: 'Inventory Optimization' },
  { name: 'Demand Forecasting' },
  { name: 'AI Research' },
  { name: 'AI Tools' },
  { name: 'AI Frameworks' },
  { name: 'AI Platforms' },
  { name: 'AI Startups' },
  { name: 'AI Trends' }
];