export const FakeShakespeare = [
  "A fair mood may dawn with a search bar's grace, yet a foul mood,too, may find its trace therein.",
  "To code, or not to code, that is the question; whether 'tis nobler in the mind to suffer the bugs and errors of outrageous fortune.",
  "All the world's a stage, and all the techies merely players; they have their exits and their entrances, and one coder in their time plays many parts.",
  "A bug by any other name would smell as foul.",
  "Cry havoc and let slip the dogs of code review.",
  "Friends, coders, countrymen, lend me your ears; I come to debug, not to praise.",
  "The fault, dear coder, is not in our stars, but in our code.",
  "Out, out, brief candle! Code is but a walking shadow, a poor player that struts and frets his hour upon the stage.",
  "There is nothing either good or bad, but coding makes it so.",
  "Though this be madness, yet there is method in't.",
  "The course of true code never did run smooth.",
  "Some are born great, some achieve greatness, and some have greatness thrust upon them by a deadline.",
  "To thine own code be true, and it must follow, as the night the day, thou canst not then be false to any bug.",
  "The lady doth protest too much, methinks, about the new framework.",
  "A little more than kin, and less than kind, is the relationship between coder and bug.",
  "When sorrows come, they come not single spies, but in battalions of error messages.",
  "The better part of valor is discretion, in the code review.",
  "Brevity is the soul of wit, and the heart of clean code.",
  "The evil that men do lives after them; the good is oft interred with their code comments.",
  "This above all: to thine own self be true, and to your code as well.",
  "The time is out of joint; O cursed spite, that ever I was born to set it right in the codebase.",
  "All that glitters is not gold, but all that compiles is not bug-free.",
  "The better part of valor is discretion, in the code review.",
  "A horse! A horse! My kingdom for a horse! Or at least a working build.",
  "The web of our life is of a mingled yarn, good and ill together, like our codebase.",
  "The golden age is before us, not behind us, if we can just fix this bug.",
  "The lunatic, the lover, and the poet are of imagination all compact, much like the coder, the tester, and the manager.",
  "The devil can cite Scripture for his purpose, and a coder can cite documentation for theirs.",
  "The course of true code never did run smooth.",
  "The fault, dear coder, is not in our stars, but in our code.",
  "The lady doth protest too much, methinks, about the new framework.",
  "The time is out of joint; O cursed spite, that ever I was born to set it right in the codebase.",
  "There is nothing either good or bad, but coding makes it so.",
  "Though this be madness, yet there is method in't.",
  "To code, or not to code, that is the question; whether 'tis nobler in the mind to suffer the bugs and errors of outrageous fortune.",
  "To thine own code be true, and it must follow, as the night the day, thou canst not then be false to any bug.",
  "When sorrows come, they come not single spies, but in battalions of error messages.",
  "All the world's a stage, and all the techies merely players; they have their exits and their entrances, and one coder in their time plays many parts.",
  "A bug by any other name would smell as foul.",
  "Cry havoc and let slip the dogs of code review.",
  "Friends, coders, countrymen, lend me your ears; I come to debug, not to praise.",
  "Out, out, brief candle! Code is but a walking shadow, a poor player that struts and frets his hour upon the stage.",
  "Some are born great, some achieve greatness, and some have greatness thrust upon them by a deadline.",
  "The evil that men do lives after them; the good is oft interred with their code comments.",
  "The golden age is before us, not behind us, if we can just fix this bug.",
  "The lunatic, the lover, and the poet are of imagination all compact, much like the coder, the tester, and the manager.",
  "The web of our life is of a mingled yarn, good and ill together, like our codebase.",
  "A horse! A horse! My kingdom for a horse! Or at least a working build.",
  "Brevity is the soul of wit, and the heart of clean code.",
  "The devil can cite Scripture for his purpose, and a coder can cite documentation for theirs.",
  "All that glitters is not gold, but all that compiles is not bug-free."
];