import { DataElementType } from "../DataElementType";

export const ResentlyViewed: DataElementType[] = [
  {
    code: "employee_performance_review",
    title: "Employee Performance Review",
    capacity: 110,
    date: new Date("2025-04-16"),
    time: "10:00:00",
    type: "dashboard",
  },
  {
    code: "monthly_sales_report",
    title: "Monthly Sales Report",
    capacity: 120,
    date: new Date("2025-04-15"),
    time: "11:00:00",
    type: "report",
  },
  {
    code: "customer_feedback_analysis",
    title: "Customer Feedback Analysis",
    capacity: 130,
    date: new Date("2025-04-14"),
    time: "12:00:00",
    type: "dataset",
  },
  {
    code: "inventory_management_dashboard",
    title: "Inventory Management Dashboard",
    capacity: 140,
    date: new Date("2025-04-13"),
    time: "13:00:00",
    type: "dashboard",
  },
  {
    code: "quarterly_financial_summary",
    title: "Quarterly Financial Summary",
    capacity: 150,
    date: new Date("2025-04-12"),
    time: "14:00:00",
    type: "report",
  },
  {
    code: "product_performance_metrics",
    title: "Product Performance Metrics",
    capacity: 160,
    date: new Date("2025-04-11"),
    time: "15:00:00",
    type: "dataset",
  },
  {
    code: "marketing_campaign_dashboard",
    title: "Marketing Campaign Dashboard",
    capacity: 170,
    date: new Date("2025-04-10"),
    time: "16:00:00",
    type: "dashboard",
  },
  {
    code: "customer_retention_report",
    title: "Customer Retention Report",
    capacity: 180,
    date: new Date("2025-04-09"),
    time: "17:00:00",
    type: "report",
  },
  {
    code: "supply_chain_analysis",
    title: "Supply Chain Analysis",
    capacity: 190,
    date: new Date("2025-04-08"),
    time: "18:00:00",
    type: "dataset",
  },
  {
    code: "revenue_forecast_dashboard",
    title: "Revenue Forecast Dashboard",
    capacity: 200,
    date: new Date("2025-04-07"),
    time: "19:00:00",
    type: "dashboard",
  },
  {
    code: "employee_engagement_report",
    title: "Employee Engagement Report",
    capacity: 210,
    date: new Date("2025-04-06"),
    time: "20:00:00",
    type: "report",
  },
  {
    code: "product_launch_analysis",
    title: "Product Launch Analysis",
    capacity: 220,
    date: new Date("2025-04-05"),
    time: "21:00:00",
    type: "dataset",
  },
  {
    code: "customer_segmentation_dashboard",
    title: "Customer Segmentation Dashboard",
    capacity: 230,
    date: new Date("2025-04-04"),
    time: "22:00:00",
    type: "dashboard",
  },
  {
    code: "financial_risk_assessment",
    title: "Financial Risk Assessment",
    capacity: 240,
    date: new Date("2025-04-03"),
    time: "23:00:00",
    type: "report",
  },
  {
    code: "market_trend_analysis",
    title: "Market Trend Analysis",
    capacity: 250,
    date: new Date("2025-04-02"),
    time: "00:00:00",
    type: "dataset",
  },
  {
    code: "team_performance_dashboard",
    title: "Team Performance Dashboard",
    capacity: 260,
    date: new Date("2025-04-01"),
    time: "01:00:00",
    type: "dashboard",
  },
  {
    code: "annual_budget_report",
    title: "Annual Budget Report",
    capacity: 270,
    date: new Date("2025-03-31"),
    time: "02:00:00",
    type: "report",
  },
  {
    code: "logistics_efficiency_metrics",
    title: "Logistics Efficiency Metrics",
    capacity: 280,
    date: new Date("2025-03-30"),
    time: "03:00:00",
    type: "dataset",
  },
  {
    code: "sales_growth_dashboard",
    title: "Sales Growth Dashboard",
    capacity: 290,
    date: new Date("2025-03-29"),
    time: "04:00:00",
    type: "dashboard",
  },
  {
    code: "customer_loyalty_report",
    title: "Customer Loyalty Report",
    capacity: 300,
    date: new Date("2025-03-28"),
    time: "05:00:00",
    type: "report",
  },
];

export const Report: DataElementType[] = [
  {
    code: "team_meeting_schedule",
    title: "Team Meeting Schedule",
    capacity: 50,
    date: new Date("2025-05-01"),
    time: "08:00:00",
    type: "dashboard",
  },
  {
    code: "weekly_sales_summary",
    title: "Weekly Sales Summary",
    capacity: 60,
    date: new Date("2025-05-02"),
    time: "09:00:00",
    type: "report",
  },
  {
    code: "customer_support_metrics",
    title: "Customer Support Metrics",
    capacity: 70,
    date: new Date("2025-05-03"),
    time: "10:00:00",
    type: "dataset",
  },
  {
    code: "inventory_status_dashboard",
    title: "Inventory Status Dashboard",
    capacity: 80,
    date: new Date("2025-05-04"),
    time: "11:00:00",
    type: "dashboard",
  },
  {
    code: "monthly_expense_report",
    title: "Monthly Expense Report",
    capacity: 90,
    date: new Date("2025-05-05"),
    time: "12:00:00",
    type: "report",
  },
  {
    code: "product_quality_analysis",
    title: "Product Quality Analysis",
    capacity: 100,
    date: new Date("2025-05-06"),
    time: "13:00:00",
    type: "dataset",
  },
  {
    code: "marketing_performance_dashboard",
    title: "Marketing Performance Dashboard",
    capacity: 110,
    date: new Date("2025-05-07"),
    time: "14:00:00",
    type: "dashboard",
  },
  {
    code: "customer_churn_report",
    title: "Customer Churn Report",
    capacity: 120,
    date: new Date("2025-05-08"),
    time: "15:00:00",
    type: "report",
  },
  {
    code: "supply_chain_efficiency",
    title: "Supply Chain Efficiency",
    capacity: 130,
    date: new Date("2025-05-09"),
    time: "16:00:00",
    type: "dataset",
  },
  {
    code: "profit_margin_dashboard",
    title: "Profit Margin Dashboard",
    capacity: 140,
    date: new Date("2025-05-10"),
    time: "17:00:00",
    type: "dashboard",
  },
  {
    code: "employee_satisfaction_report",
    title: "Employee Satisfaction Report",
    capacity: 150,
    date: new Date("2025-05-11"),
    time: "18:00:00",
    type: "report",
  },
  {
    code: "product_demand_forecast",
    title: "Product Demand Forecast",
    capacity: 160,
    date: new Date("2025-05-12"),
    time: "19:00:00",
    type: "dataset",
  },
];

export const DataSet: DataElementType[] = [
  {
    code: "project_timeline_dashboard",
    title: "Project Timeline Dashboard",
    capacity: 75,
    date: new Date("2025-05-15"),
    time: "09:00:00",
    type: "dashboard",
  },
  {
    code: "regional_sales_report",
    title: "Regional Sales Report",
    capacity: 85,
    date: new Date("2025-05-14"),
    time: "10:00:00",
    type: "report",
  },
  {
    code: "customer_behavior_analysis",
    title: "Customer Behavior Analysis",
    capacity: 95,
    date: new Date("2025-05-13"),
    time: "11:00:00",
    type: "dataset",
  },
  {
    code: "supply_chain_dashboard",
    title: "Supply Chain Dashboard",
    capacity: 105,
    date: new Date("2025-05-12"),
    time: "12:00:00",
    type: "dashboard",
  },
  {
    code: "annual_revenue_report",
    title: "Annual Revenue Report",
    capacity: 115,
    date: new Date("2025-05-11"),
    time: "13:00:00",
    type: "report",
  },
  {
    code: "product_sales_analysis",
    title: "Product Sales Analysis",
    capacity: 125,
    date: new Date("2025-05-10"),
    time: "14:00:00",
    type: "dataset",
  },
  {
    code: "marketing_strategy_dashboard",
    title: "Marketing Strategy Dashboard",
    capacity: 135,
    date: new Date("2025-05-09"),
    time: "15:00:00",
    type: "dashboard",
  },
  {
    code: "customer_satisfaction_report",
    title: "Customer Satisfaction Report",
    capacity: 145,
    date: new Date("2025-05-08"),
    time: "16:00:00",
    type: "report",
  },
  {
    code: "inventory_turnover_analysis",
    title: "Inventory Turnover Analysis",
    capacity: 155,
    date: new Date("2025-05-07"),
    time: "17:00:00",
    type: "dataset",
  },
  {
    code: "profitability_dashboard",
    title: "Profitability Dashboard",
    capacity: 165,
    date: new Date("2025-05-06"),
    time: "18:00:00",
    type: "dashboard",
  },
];

export const Empty: DataElementType[] = [];

export const Example_DataElementArray = {
  ResentlyViewed,
  Report,
  DataSet,
  Empty,
}