import { TreeNodeType } from "../TreeNodeType";

const Long_zh: TreeNodeType = {
  id: "root",
  name: "业务运营数据",
  dataCount: 100,
  isSensitive: false,
  dataLevel: "Public",
  children: [
    {
      id: "node-1",
      name: "员工相关数据",
      dataCount: 1,
      isSensitive: false,
      dataLevel: "Public",
      children: [
        {
          id: "node-1-1",
          name: "员工身份相关数据",
          dataCount: 1,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
      ],
    },
    {
      id: "node-2",
      name: "数据表属性类相关信息",
      dataCount: 5,
      isSensitive: false,
      dataLevel: "Public",
      children: [],
    },
    {
      id: "node-3",
      name: "用户相关数据",
      dataCount: 44,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [
        {
          id: "node-3-1",
          name: "用户关系管理数据",
          dataCount: 31,
          isSensitive: true,
          dataLevel: "Confidential",
          children: [
            {
              id: "node-3-1-1",
              name: "用户密码及关联信息",
              dataCount: 2,
              isSensitive: true,
              dataLevel: "Restricted",
              children: [],
            },
            {
              id: "node-3-1-2",
              name: "用户消费偏好分析",
              dataCount: 3,
              isSensitive: false,
              dataLevel: "Public",
              children: [],
            },
            {
              id: "node-3-1-3",
              name: "用户网络行为分析",
              dataCount: 3,
              isSensitive: true,
              dataLevel: "Confidential",
              children: [],
            },
            {
              id: "node-3-1-4",
              name: "用户身份相关数据",
              dataCount: 23,
              isSensitive: true,
              dataLevel: "Confidential",
              children: [],
            },
          ],
        },
        {
          id: "node-3-2",
          name: "用户活动数据",
          dataCount: 13,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
      ],
    },
    {
      id: "node-4",
      name: "财务相关数据",
      dataCount: 20,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [
        {
          id: "node-4-1",
          name: "收入与支出数据",
          dataCount: 10,
          isSensitive: true,
          dataLevel: "Restricted",
          children: [],
        },
        {
          id: "node-4-2",
          name: "税务相关数据",
          dataCount: 10,
          isSensitive: true,
          dataLevel: "Confidential",
          children: [],
        },
      ],
    },
    {
      id: "node-5",
      name: "市场营销数据",
      dataCount: 15,
      isSensitive: false,
      dataLevel: "Public",
      children: [
        {
          id: "node-5-1",
          name: "广告投放数据",
          dataCount: 8,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
        {
          id: "node-5-2",
          name: "客户反馈数据",
          dataCount: 7,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
      ],
    },
    {
      id: "node-6",
      name: "供应链数据",
      dataCount: 25,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [
        {
          id: "node-6-1",
          name: "库存管理数据",
          dataCount: 15,
          isSensitive: true,
          dataLevel: "Confidential",
          children: [],
        },
        {
          id: "node-6-2",
          name: "物流跟踪数据",
          dataCount: 10,
          isSensitive: true,
          dataLevel: "Restricted",
          children: [],
        },
      ],
    },
  ],
};

const Long_en: TreeNodeType = {
  id: "root",
  name: "Business Operations Data",
  dataCount: 100,
  isSensitive: false,
  dataLevel: "Public",
  children: [
    {
      id: "node-1",
      name: "Employee Related Data",
      dataCount: 1,
      isSensitive: false,
      dataLevel: "Public",
      children: [
        {
          id: "node-1-1",
          name: "Employee Identity Related Data",
          dataCount: 1,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
      ],
    },
    {
      id: "node-2",
      name: "Data Table Attribute Information",
      dataCount: 5,
      isSensitive: false,
      dataLevel: "Public",
      children: [],
    },
    {
      id: "node-3",
      name: "User Related Data",
      dataCount: 44,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [
        {
          id: "node-3-1",
          name: "User Relationship Management Data",
          dataCount: 31,
          isSensitive: true,
          dataLevel: "Confidential",
          children: [
            {
              id: "node-3-1-1",
              name: "User Password and Associated Information",
              dataCount: 2,
              isSensitive: true,
              dataLevel: "Restricted",
              children: [],
            },
            {
              id: "node-3-1-2",
              name: "User Consumption Preference Analysis",
              dataCount: 3,
              isSensitive: false,
              dataLevel: "Public",
              children: [],
            },
            {
              id: "node-3-1-3",
              name: "User Online Behavior Analysis",
              dataCount: 3,
              isSensitive: true,
              dataLevel: "Confidential",
              children: [],
            },
            {
              id: "node-3-1-4",
              name: "User Identity Related Data",
              dataCount: 23,
              isSensitive: true,
              dataLevel: "Confidential",
              children: [],
            },
          ],
        },
        {
          id: "node-3-2",
          name: "User Activity Data",
          dataCount: 13,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
      ],
    },
    {
      id: "node-4",
      name: "Financial Related Data",
      dataCount: 20,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [
        {
          id: "node-4-1",
          name: "Income and Expenditure Data",
          dataCount: 10,
          isSensitive: true,
          dataLevel: "Restricted",
          children: [],
        },
        {
          id: "node-4-2",
          name: "Tax Related Data",
          dataCount: 10,
          isSensitive: true,
          dataLevel: "Confidential",
          children: [],
        },
      ],
    },
    {
      id: "node-5",
      name: "Marketing Data",
      dataCount: 15,
      isSensitive: false,
      dataLevel: "Public",
      children: [
        {
          id: "node-5-1",
          name: "Advertising Data",
          dataCount: 8,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
        {
          id: "node-5-2",
          name: "Customer Feedback Data",
          dataCount: 7,
          isSensitive: false,
          dataLevel: "Public",
          children: [],
        },
      ],
    },
    {
      id: "node-6",
      name: "Supply Chain Data",
      dataCount: 25,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [
        {
          id: "node-6-1",
          name: "Inventory Management Data",
          dataCount: 15,
          isSensitive: true,
          dataLevel: "Confidential",
          children: [],
        },
        {
          id: "node-6-2",
          name: "Logistics Tracking Data",
          dataCount: 10,
          isSensitive: true,
          dataLevel: "Restricted",
          children: [],
        },
      ],
    },
  ],
};

const Short_zh: TreeNodeType = {
  id: "short-root",
  name: "简短示例数据",
  dataCount: 10,
  isSensitive: false,
  dataLevel: "Public",
  children: [
    {
      id: "short-node-1",
      name: "分类一",
      dataCount: 5,
      isSensitive: false,
      dataLevel: "Public",
      children: [],
    },
    {
      id: "short-node-2",
      name: "分类二",
      dataCount: 5,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [],
    },
  ],
};

const Short_en: TreeNodeType = {
  id: "short-root",
  name: "Short Example Data",
  dataCount: 10,
  isSensitive: false,
  dataLevel: "Public",
  children: [
    {
      id: "short-node-1",
      name: "Category One",
      dataCount: 5,
      isSensitive: false,
      dataLevel: "Public",
      children: [],
    },
    {
      id: "short-node-2",
      name: "Category Two",
      dataCount: 5,
      isSensitive: true,
      dataLevel: "Confidential",
      children: [],
    },
  ],
};

export const Example_TreeNodeData = {
  Long_zh,
  Long_en,
  Short_zh,
  Short_en,
};